// Phase 2 + Phase 3 (3A) — Convex schema.
//
// 14 business entities. Every business table carries `workspaceId`
// (multi-tenant boundary) and `externalId` (stable, environment-portable
// identifier from `lib/mock/`). Convex's auto-generated `_id` is used
// for foreign keys and reactivity; `externalId` is what the URL layer
// and tests reference.
//
// The user identity table (`user`) lives in the Better Auth component
// (see `convex/betterAuth/schema.ts`). It is NOT defined here — it is
// generated by `npx @better-auth/cli generate`. We reference it from
// the main schema as `v.id("user")`.
//
// Indexes are declared here once and queried via
// `ctx.db.query(table).withIndex(...)`. The `indexes.test.ts` test
// suite proves every `withIndex` call has a matching `.index()`
// declaration.

import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

// ---------- shared validators ----------

export const statusKey = v.union(
  v.literal("backlog"),
  v.literal("todo"),
  v.literal("in_progress"),
  v.literal("in_review"),
  v.literal("done"),
  v.literal("cancelled"),
);

export const priorityKey = v.union(
  v.literal("urgent"),
  v.literal("high"),
  v.literal("medium"),
  v.literal("low"),
  v.literal("none"),
);

export const role = v.union(
  v.literal("owner"),
  v.literal("admin"),
  v.literal("member"),
  v.literal("guest"),
);

export const userStatus = v.union(
  v.literal("online"),
  v.literal("away"),
  v.literal("offline"),
);

export const cycleStatus = v.union(
  v.literal("upcoming"),
  v.literal("active"),
  v.literal("completed"),
);

export const notificationType = v.union(
  v.literal("assignment"),
  v.literal("mention"),
  v.literal("status_change"),
  v.literal("comment"),
  v.literal("due"),
  v.literal("review_request"),
  v.literal("review"),
  v.literal("status"),
);

export const activityVerb = v.union(
  v.literal("created"),
  v.literal("status_changed"),
  v.literal("assignee_changed"),
  v.literal("priority_changed"),
  v.literal("label_added"),
  v.literal("label_removed"),
  v.literal("commented"),
  v.literal("mentioned"),
  v.literal("due_changed"),
  v.literal("title_changed"),
);

// ---------- schema ----------

export default defineSchema({
  // 1. Top-level tenant. Every business table points here.
  // `ownerId` is the Better Auth user _id (string reference to the
  // `user` table that lives in the Better Auth component).
  workspaces: defineTable({
    externalId: v.string(),
    name: v.string(),
    slug: v.string(),
    ownerId: v.string(), // Better Auth user _id (component table: `user`)
    archivedAt: v.optional(v.number()),
  })
    .index("by_slug", ["slug"])
    .index("by_externalId", ["externalId"]),

  // 2. Join: user ↔ workspace, with role. The tenant boundary is enforced
  // by `requireWorkspace` (see `convex/_lib/tenancy.ts`).
  // `userId` and `invitedBy` are Better Auth user _ids.
  memberships: defineTable({
    externalId: v.string(),
    userId: v.string(), // Better Auth user _id
    workspaceId: v.id("workspaces"),
    role,
    invitedBy: v.optional(v.string()),
    joinedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_workspace", ["workspaceId"])
    .index("by_user_workspace", ["userId", "workspaceId"])
    .index("by_externalId", ["externalId"]),

  // 3. A project (Linear calls this a "team"). Belongs to a workspace.
  projects: defineTable({
    externalId: v.string(),
    workspaceId: v.id("workspaces"),
    key: v.string(), // "ENG", "DSG" — used in issue keys like "ENG-1001"
    name: v.string(),
    description: v.string(),
    iconLetter: v.string(),
    iconColor: v.string(),
    lead: v.string(), // Better Auth user _id
    archivedAt: v.optional(v.number()),
  })
    .index("by_workspace", ["workspaceId"])
    .index("by_workspace_key", ["workspaceId", "key"])
    .index("by_workspace_archived", ["workspaceId", "archivedAt"])
    .index("by_externalId", ["externalId"]),

  // 4. Per-project membership (in addition to workspace membership).
  // `projectMembers` is workspaceId-scoped for tenant isolation tests.
  projectMembers: defineTable({
    externalId: v.string(),
    workspaceId: v.id("workspaces"),
    projectId: v.id("projects"),
    userId: v.string(), // Better Auth user _id
  })
    .index("by_project", ["projectId"])
    .index("by_user", ["userId"])
    .index("by_project_user", ["projectId", "userId"])
    .index("by_workspace", ["workspaceId"]),

  // 5. Per-project labels.
  labels: defineTable({
    externalId: v.string(),
    workspaceId: v.id("workspaces"),
    projectId: v.id("projects"),
    name: v.string(),
    color: v.string(),
  })
    .index("by_workspace", ["workspaceId"])
    .index("by_project", ["projectId"])
    .index("by_externalId", ["externalId"]),

  // 6. The primary entity. Every list view queries through this table.
  // `assigneeIds[]` and `labelIds[]` are denormalized arrays for fast
  // reads; the corresponding join tables (`issueAssignees`) power reverse
  // lookups. All user references are Better Auth user _ids.
  issues: defineTable({
    externalId: v.string(),
    workspaceId: v.id("workspaces"),
    projectId: v.id("projects"),
    cycleId: v.optional(v.id("cycles")),
    parentId: v.optional(v.id("issues")),
    key: v.string(), // "ENG-1001"
    number: v.number(),
    title: v.string(),
    description: v.string(),
    status: statusKey,
    priority: priorityKey,
    assigneeIds: v.array(v.string()), // Better Auth user _ids
    labelIds: v.array(v.id("labels")),
    estimatePoints: v.optional(v.number()),
    dueDate: v.optional(v.string()),
    blockedBy: v.array(v.id("issues")),
    subIssueIds: v.array(v.id("issues")),
    pr: v.optional(
      v.object({
        number: v.number(),
        repo: v.string(),
        status: v.union(
          v.literal("open"),
          v.literal("merged"),
          v.literal("closed"),
        ),
      }),
    ),
    urlCount: v.number(),
    attachmentCount: v.number(),
    authorId: v.string(), // Better Auth user _id
    createdAt: v.number(),
    updatedAt: v.number(),
    archivedAt: v.optional(v.number()),
  })
    .index("by_workspace", ["workspaceId"])
    .index("by_workspace_status", ["workspaceId", "status"])
    .index("by_workspace_project", ["workspaceId", "projectId"])
    .index("by_workspace_project_status", ["workspaceId", "projectId", "status"])
    .index("by_workspace_assignee", ["workspaceId", "assigneeIds"])
    .index("by_workspace_label", ["workspaceId", "labelIds"])
    .index("by_workspace_due", ["workspaceId", "dueDate"])
    .index("by_project_number", ["projectId", "number"])
    .index("by_externalId", ["externalId"]),

  // 7. Join: issue ↔ assignee. Powers "issues assigned to me in workspace X".
  // `workspaceId` is denormalized for index-only tenant scoping.
  issueAssignees: defineTable({
    workspaceId: v.id("workspaces"),
    issueId: v.id("issues"),
    userId: v.string(), // Better Auth user _id
  })
    .index("by_issue", ["issueId"])
    .index("by_user_workspace", ["userId", "workspaceId"]),

  // 8. Sprints per project.
  cycles: defineTable({
    externalId: v.string(),
    workspaceId: v.id("workspaces"),
    projectId: v.id("projects"),
    number: v.number(),
    name: v.string(),
    startDate: v.string(),
    endDate: v.string(),
    status: cycleStatus,
    goal: v.string(),
  })
    .index("by_workspace", ["workspaceId"])
    .index("by_project", ["projectId"])
    .index("by_externalId", ["externalId"]),

  // 9. Join: cycle ↔ issues.
  cycleIssues: defineTable({
    workspaceId: v.id("workspaces"),
    cycleId: v.id("cycles"),
    issueId: v.id("issues"),
  })
    .index("by_cycle", ["cycleId"])
    .index("by_issue", ["issueId"]),

  // 10. User-saved filter combos. `filter` is `v.any()` for now; Phase 4
  // re-types it to a discriminated union of the URL grammar.
  savedViews: defineTable({
    externalId: v.string(),
    workspaceId: v.id("workspaces"),
    ownerId: v.string(), // Better Auth user _id
    name: v.string(),
    filter: v.any(),
    group: v.string(),
    sortKey: v.string(),
    sortDir: v.string(),
    starred: v.boolean(),
    createdAt: v.number(),
  })
    .index("by_workspace_owner", ["workspaceId", "ownerId"])
    .index("by_workspace_owner_starred", ["workspaceId", "ownerId", "starred"])
    .index("by_externalId", ["externalId"]),

  // 11. Issue comments. `createdAt` is a number for index ordering.
  // `reactions.users` is Better Auth user _ids.
  comments: defineTable({
    externalId: v.string(),
    workspaceId: v.id("workspaces"),
    issueId: v.id("issues"),
    authorId: v.string(), // Better Auth user _id
    body: v.string(),
    createdAt: v.number(),
    reactions: v.array(
      v.object({
        emoji: v.string(),
        count: v.number(),
        users: v.array(v.string()), // Better Auth user _ids
      }),
    ),
  })
    .index("by_workspace_issue", ["workspaceId", "issueId"])
    .index("by_workspace_issue_created", ["workspaceId", "issueId", "createdAt"])
    .index("by_externalId", ["externalId"]),

  // 12. Inbox items. `by_user_workspace_created` powers the inbox query.
  notifications: defineTable({
    externalId: v.string(),
    workspaceId: v.id("workspaces"),
    userId: v.string(), // recipient — Better Auth user _id
    type: notificationType,
    issueId: v.optional(v.id("issues")),
    actorId: v.optional(v.string()), // who did it — Better Auth user _id
    actorName: v.string(),
    preview: v.optional(v.string()),
    read: v.boolean(),
    snoozedUntil: v.optional(v.number()),
    createdAt: v.number(),
  })
    .index("by_user_read", ["userId", "read"])
    .index("by_user_workspace_created", ["userId", "workspaceId", "createdAt"])
    .index("by_externalId", ["externalId"]),

  // 13. Audit trail. Every mutation writes a row. `objectType` + `objectId`
  // index powers "what happened to this issue". `actorId` is a Better Auth
  // user _id; `objectId` is string-typed to allow cross-table references.
  activities: defineTable({
    externalId: v.string(),
    workspaceId: v.id("workspaces"),
    actorId: v.string(), // Better Auth user _id
    verb: activityVerb,
    objectType: v.string(), // "issue" | "cycle" | "project" | "comment"
    objectId: v.string(),
    before: v.optional(v.any()),
    after: v.optional(v.any()),
    createdAt: v.number(),
  })
    .index("by_workspace_created", ["workspaceId", "createdAt"])
    .index("by_workspace_object", ["workspaceId", "objectType", "objectId"])
    .index("by_externalId", ["externalId"]),

  // 14. Workspace invitations. Created by `invite` mutation (3E), accepted
  // by the `acceptInvite` mutation. Tokens are 256-bit; the `email` is the
  // invitee's address. `invitedBy` is a Better Auth user _id.
  invitations: defineTable({
    externalId: v.string(),
    workspaceId: v.id("workspaces"),
    email: v.string(),
    role,
    token: v.string(), // hashed at rest; raw token only sent in email link
    invitedBy: v.string(), // Better Auth user _id
    expiresAt: v.number(),
    acceptedAt: v.optional(v.number()),
    revokedAt: v.optional(v.number()),
    createdAt: v.number(),
  })
    .index("by_workspace", ["workspaceId"])
    .index("by_token", ["token"])
    .index("by_email_workspace", ["email", "workspaceId"])
    .index("by_externalId", ["externalId"]),

  // 15. TOTP two-factor secrets. One row per user with 2FA enabled.
  // `secret` is the base32-encoded shared secret (encrypted at rest in
  // production via the audit hook). `backupCodes` is an array of hashed
  // single-use recovery codes.
  twoFactorSecrets: defineTable({
    userId: v.string(), // Better Auth user _id
    secret: v.string(),
    enabled: v.boolean(),
    backupCodes: v.array(v.string()), // hashed; one-time use
    enrolledAt: v.number(),
    lastUsedAt: v.optional(v.number()),
  })
    .index("by_user", ["userId"]),

  // 16. Rate limit counters. The in-memory rate limiter in 3A is replaced
  // by this table in production (3G) so the limits apply across all
  // Convex nodes.
  rateLimits: defineTable({
    key: v.string(), // e.g. "sign-in:1.2.3.4" or "magic-link:user@example.com"
    windowStart: v.number(),
    count: v.number(),
  })
    .index("by_key", ["key"])
    .index("by_window", ["windowStart"]),

  // 17. Email audit log. Every transactional email sent is recorded here
  // for support debugging ("did the user get the verify link?") and for
  // the in-app "Email history" view in settings (3H).
  emails: defineTable({
    workspaceId: v.optional(v.id("workspaces")),
    userId: v.optional(v.string()), // Better Auth user _id (recipient)
    template: v.string(), // "welcome" | "magic-link" | "verify-email" | "reset-password" | "workspace-invite" | "new-device"
    to: v.string(),
    subject: v.string(),
    status: v.union(
      v.literal("queued"),
      v.literal("sent"),
      v.literal("delivered"),
      v.literal("bounced"),
      v.literal("complained"),
    ),
    resendId: v.optional(v.string()),
    sentAt: v.number(),
    deliveredAt: v.optional(v.number()),
    bouncedAt: v.optional(v.number()),
  })
    .index("by_user", ["userId"])
    .index("by_workspace", ["workspaceId"])
    .index("by_status", ["status"]),
});
